/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CheckInPeriod = IDL.Variant({
  'Q1' : IDL.Null,
  'Q2' : IDL.Null,
  'Q3' : IDL.Null,
  'Q4Annual' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const ManagerCheckIn = IDL.Record({
  'id' : IDL.Text,
  'period' : CheckInPeriod,
  'createdAt' : Timestamp,
  'goalId' : IDL.Text,
  'comment' : IDL.Text,
  'employeeId' : UserId,
  'managerId' : UserId,
});
export const Result_10 = IDL.Variant({
  'ok' : ManagerCheckIn,
  'err' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const UoMType = IDL.Variant({
  'Percent' : IDL.Null,
  'Numeric' : IDL.Null,
  'Timeline' : IDL.Null,
  'ZeroBased' : IDL.Null,
});
export const UoMDirection = IDL.Variant({ 'Max' : IDL.Null, 'Min' : IDL.Null });
export const GoalStatus = IDL.Variant({
  'ApprovedLocked' : IDL.Null,
  'UnderReview' : IDL.Null,
  'Draft' : IDL.Null,
  'ReturnedForRework' : IDL.Null,
  'Submitted' : IDL.Null,
});
export const Goal = IDL.Record({
  'id' : IDL.Text,
  'status' : GoalStatus,
  'weightage' : IDL.Float64,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'uomType' : UoMType,
  'description' : IDL.Text,
  'sharedFromId' : IDL.Opt(IDL.Text),
  'isShared' : IDL.Bool,
  'uomDirection' : IDL.Opt(UoMDirection),
  'updatedAt' : Timestamp,
  'target' : IDL.Float64,
  'employeeId' : UserId,
  'thrustAreaId' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : Goal, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'Employee' : IDL.Null,
  'Admin' : IDL.Null,
  'Manager' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'demoKey' : IDL.Text,
  'managerId' : IDL.Opt(UserId),
  'department' : IDL.Text,
});
export const AchievementStatus = IDL.Variant({
  'OnTrack' : IDL.Null,
  'Completed' : IDL.Null,
  'NotStarted' : IDL.Null,
});
export const Achievement = IDL.Record({
  'id' : IDL.Text,
  'actual' : IDL.Float64,
  'completionDate' : IDL.Opt(Timestamp),
  'period' : CheckInPeriod,
  'progressScore' : IDL.Float64,
  'goalId' : IDL.Text,
  'achievementStatus' : AchievementStatus,
  'updatedAt' : Timestamp,
  'employeeId' : UserId,
});
export const AchievementReportRow = IDL.Record({
  'user' : User,
  'achievements' : IDL.Vec(Achievement),
  'goals' : IDL.Vec(Goal),
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Vec(AchievementReportRow),
  'err' : IDL.Text,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Text,
  'field' : IDL.Text,
  'changedByName' : IDL.Text,
  'oldValue' : IDL.Text,
  'changedBy' : UserId,
  'newValue' : IDL.Text,
  'goalId' : IDL.Text,
  'timestamp' : Timestamp,
});
export const Result_8 = IDL.Variant({
  'ok' : IDL.Vec(ManagerCheckIn),
  'err' : IDL.Text,
});
export const CompletionDashboardRow = IDL.Record({
  'q2Done' : IDL.Bool,
  'submitted' : IDL.Bool,
  'q4Done' : IDL.Bool,
  'user' : User,
  'q1Done' : IDL.Bool,
  'approved' : IDL.Bool,
  'q3Done' : IDL.Bool,
});
export const Result_7 = IDL.Variant({
  'ok' : IDL.Vec(CompletionDashboardRow),
  'err' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
export const Result_6 = IDL.Variant({
  'ok' : IDL.Vec(Achievement),
  'err' : IDL.Text,
});
export const Result_5 = IDL.Variant({ 'ok' : IDL.Vec(Goal), 'err' : IDL.Text });
export const Result_4 = IDL.Variant({ 'ok' : IDL.Vec(User), 'err' : IDL.Text });
export const ThrustArea = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Result_3 = IDL.Variant({ 'ok' : Achievement, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addCheckInComment' : IDL.Func(
      [IDL.Text, IDL.Principal, CheckInPeriod, IDL.Text],
      [Result_10],
      [],
    ),
  'adminUnlockGoals' : IDL.Func([IDL.Principal, IDL.Text], [Result_1], []),
  'createGoal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        UoMType,
        IDL.Opt(UoMDirection),
        IDL.Float64,
        IDL.Float64,
      ],
      [Result],
      [],
    ),
  'getAchievementReport' : IDL.Func([CheckInPeriod], [Result_9], []),
  'getAuditLog' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(AuditLog)], ['query']),
  'getCheckInComments' : IDL.Func(
      [IDL.Principal, CheckInPeriod],
      [Result_8],
      ['query'],
    ),
  'getCompletionDashboard' : IDL.Func([], [Result_7], []),
  'getCurrentUser' : IDL.Func([], [Result_2], []),
  'getEmployeeAchievements' : IDL.Func(
      [IDL.Principal, CheckInPeriod],
      [Result_6],
      ['query'],
    ),
  'getEmployeeGoals' : IDL.Func([IDL.Principal], [Result_5], ['query']),
  'getMyAchievements' : IDL.Func([CheckInPeriod], [Result_6], ['query']),
  'getMyGoals' : IDL.Func([], [Result_5], ['query']),
  'getMyTeam' : IDL.Func([], [Result_4], []),
  'getThrustAreas' : IDL.Func([], [IDL.Vec(ThrustArea)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'logAchievement' : IDL.Func(
      [
        IDL.Text,
        CheckInPeriod,
        IDL.Float64,
        IDL.Opt(IDL.Int),
        AchievementStatus,
      ],
      [Result_3],
      [],
    ),
  'loginAsDemo' : IDL.Func([IDL.Text], [Result_2], []),
  'managerApproveGoals' : IDL.Func([IDL.Principal], [Result_1], []),
  'managerEditGoal' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64)],
      [Result],
      [],
    ),
  'managerReturnGoals' : IDL.Func([IDL.Principal, IDL.Text], [Result_1], []),
  'pushSharedGoal' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Principal)],
      [Result_1],
      [],
    ),
  'submitGoalsForApproval' : IDL.Func([], [Result_1], []),
  'updateGoal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        UoMType,
        IDL.Opt(UoMDirection),
        IDL.Float64,
        IDL.Float64,
      ],
      [Result],
      [],
    ),
  'updateSharedGoalWeightage' : IDL.Func([IDL.Text, IDL.Float64], [Result], []),
  'whoami' : IDL.Func([], [IDL.Principal], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CheckInPeriod = IDL.Variant({
    'Q1' : IDL.Null,
    'Q2' : IDL.Null,
    'Q3' : IDL.Null,
    'Q4Annual' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const ManagerCheckIn = IDL.Record({
    'id' : IDL.Text,
    'period' : CheckInPeriod,
    'createdAt' : Timestamp,
    'goalId' : IDL.Text,
    'comment' : IDL.Text,
    'employeeId' : UserId,
    'managerId' : UserId,
  });
  const Result_10 = IDL.Variant({ 'ok' : ManagerCheckIn, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const UoMType = IDL.Variant({
    'Percent' : IDL.Null,
    'Numeric' : IDL.Null,
    'Timeline' : IDL.Null,
    'ZeroBased' : IDL.Null,
  });
  const UoMDirection = IDL.Variant({ 'Max' : IDL.Null, 'Min' : IDL.Null });
  const GoalStatus = IDL.Variant({
    'ApprovedLocked' : IDL.Null,
    'UnderReview' : IDL.Null,
    'Draft' : IDL.Null,
    'ReturnedForRework' : IDL.Null,
    'Submitted' : IDL.Null,
  });
  const Goal = IDL.Record({
    'id' : IDL.Text,
    'status' : GoalStatus,
    'weightage' : IDL.Float64,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'uomType' : UoMType,
    'description' : IDL.Text,
    'sharedFromId' : IDL.Opt(IDL.Text),
    'isShared' : IDL.Bool,
    'uomDirection' : IDL.Opt(UoMDirection),
    'updatedAt' : Timestamp,
    'target' : IDL.Float64,
    'employeeId' : UserId,
    'thrustAreaId' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : Goal, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'Employee' : IDL.Null,
    'Admin' : IDL.Null,
    'Manager' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'demoKey' : IDL.Text,
    'managerId' : IDL.Opt(UserId),
    'department' : IDL.Text,
  });
  const AchievementStatus = IDL.Variant({
    'OnTrack' : IDL.Null,
    'Completed' : IDL.Null,
    'NotStarted' : IDL.Null,
  });
  const Achievement = IDL.Record({
    'id' : IDL.Text,
    'actual' : IDL.Float64,
    'completionDate' : IDL.Opt(Timestamp),
    'period' : CheckInPeriod,
    'progressScore' : IDL.Float64,
    'goalId' : IDL.Text,
    'achievementStatus' : AchievementStatus,
    'updatedAt' : Timestamp,
    'employeeId' : UserId,
  });
  const AchievementReportRow = IDL.Record({
    'user' : User,
    'achievements' : IDL.Vec(Achievement),
    'goals' : IDL.Vec(Goal),
  });
  const Result_9 = IDL.Variant({
    'ok' : IDL.Vec(AchievementReportRow),
    'err' : IDL.Text,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Text,
    'field' : IDL.Text,
    'changedByName' : IDL.Text,
    'oldValue' : IDL.Text,
    'changedBy' : UserId,
    'newValue' : IDL.Text,
    'goalId' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const Result_8 = IDL.Variant({
    'ok' : IDL.Vec(ManagerCheckIn),
    'err' : IDL.Text,
  });
  const CompletionDashboardRow = IDL.Record({
    'q2Done' : IDL.Bool,
    'submitted' : IDL.Bool,
    'q4Done' : IDL.Bool,
    'user' : User,
    'q1Done' : IDL.Bool,
    'approved' : IDL.Bool,
    'q3Done' : IDL.Bool,
  });
  const Result_7 = IDL.Variant({
    'ok' : IDL.Vec(CompletionDashboardRow),
    'err' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Vec(Achievement),
    'err' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Vec(Goal), 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Vec(User), 'err' : IDL.Text });
  const ThrustArea = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : Achievement, 'err' : IDL.Text });
  
  return IDL.Service({
    'addCheckInComment' : IDL.Func(
        [IDL.Text, IDL.Principal, CheckInPeriod, IDL.Text],
        [Result_10],
        [],
      ),
    'adminUnlockGoals' : IDL.Func([IDL.Principal, IDL.Text], [Result_1], []),
    'createGoal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          UoMType,
          IDL.Opt(UoMDirection),
          IDL.Float64,
          IDL.Float64,
        ],
        [Result],
        [],
      ),
    'getAchievementReport' : IDL.Func([CheckInPeriod], [Result_9], []),
    'getAuditLog' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'getCheckInComments' : IDL.Func(
        [IDL.Principal, CheckInPeriod],
        [Result_8],
        ['query'],
      ),
    'getCompletionDashboard' : IDL.Func([], [Result_7], []),
    'getCurrentUser' : IDL.Func([], [Result_2], []),
    'getEmployeeAchievements' : IDL.Func(
        [IDL.Principal, CheckInPeriod],
        [Result_6],
        ['query'],
      ),
    'getEmployeeGoals' : IDL.Func([IDL.Principal], [Result_5], ['query']),
    'getMyAchievements' : IDL.Func([CheckInPeriod], [Result_6], ['query']),
    'getMyGoals' : IDL.Func([], [Result_5], ['query']),
    'getMyTeam' : IDL.Func([], [Result_4], []),
    'getThrustAreas' : IDL.Func([], [IDL.Vec(ThrustArea)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'logAchievement' : IDL.Func(
        [
          IDL.Text,
          CheckInPeriod,
          IDL.Float64,
          IDL.Opt(IDL.Int),
          AchievementStatus,
        ],
        [Result_3],
        [],
      ),
    'loginAsDemo' : IDL.Func([IDL.Text], [Result_2], []),
    'managerApproveGoals' : IDL.Func([IDL.Principal], [Result_1], []),
    'managerEditGoal' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64)],
        [Result],
        [],
      ),
    'managerReturnGoals' : IDL.Func([IDL.Principal, IDL.Text], [Result_1], []),
    'pushSharedGoal' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Principal)],
        [Result_1],
        [],
      ),
    'submitGoalsForApproval' : IDL.Func([], [Result_1], []),
    'updateGoal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          UoMType,
          IDL.Opt(UoMDirection),
          IDL.Float64,
          IDL.Float64,
        ],
        [Result],
        [],
      ),
    'updateSharedGoalWeightage' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [Result],
        [],
      ),
    'whoami' : IDL.Func([], [IDL.Principal], []),
  });
};

export const init = ({ IDL }) => { return []; };