/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : string,
  'actual' : number,
  'completionDate' : [] | [Timestamp],
  'period' : CheckInPeriod,
  'progressScore' : number,
  'goalId' : string,
  'achievementStatus' : AchievementStatus,
  'updatedAt' : Timestamp,
  'employeeId' : UserId,
}
export interface AchievementReportRow {
  'user' : User,
  'achievements' : Array<Achievement>,
  'goals' : Array<Goal>,
}
export type AchievementStatus = { 'OnTrack' : null } |
  { 'Completed' : null } |
  { 'NotStarted' : null };
export interface AuditLog {
  'id' : string,
  'field' : string,
  'changedByName' : string,
  'oldValue' : string,
  'changedBy' : UserId,
  'newValue' : string,
  'goalId' : string,
  'timestamp' : Timestamp,
}
export type CheckInPeriod = { 'Q1' : null } |
  { 'Q2' : null } |
  { 'Q3' : null } |
  { 'Q4Annual' : null };
export interface CompletionDashboardRow {
  'q2Done' : boolean,
  'submitted' : boolean,
  'q4Done' : boolean,
  'user' : User,
  'q1Done' : boolean,
  'approved' : boolean,
  'q3Done' : boolean,
}
export interface Goal {
  'id' : string,
  'status' : GoalStatus,
  'weightage' : number,
  'title' : string,
  'createdAt' : Timestamp,
  'uomType' : UoMType,
  'description' : string,
  'sharedFromId' : [] | [string],
  'isShared' : boolean,
  'uomDirection' : [] | [UoMDirection],
  'updatedAt' : Timestamp,
  'target' : number,
  'employeeId' : UserId,
  'thrustAreaId' : string,
}
export type GoalStatus = { 'ApprovedLocked' : null } |
  { 'UnderReview' : null } |
  { 'Draft' : null } |
  { 'ReturnedForRework' : null } |
  { 'Submitted' : null };
export interface ManagerCheckIn {
  'id' : string,
  'period' : CheckInPeriod,
  'createdAt' : Timestamp,
  'goalId' : string,
  'comment' : string,
  'employeeId' : UserId,
  'managerId' : UserId,
}
export type Result = { 'ok' : Goal } |
  { 'err' : string };
export type Result_1 = { 'ok' : boolean } |
  { 'err' : string };
export type Result_10 = { 'ok' : ManagerCheckIn } |
  { 'err' : string };
export type Result_2 = { 'ok' : User } |
  { 'err' : string };
export type Result_3 = { 'ok' : Achievement } |
  { 'err' : string };
export type Result_4 = { 'ok' : Array<User> } |
  { 'err' : string };
export type Result_5 = { 'ok' : Array<Goal> } |
  { 'err' : string };
export type Result_6 = { 'ok' : Array<Achievement> } |
  { 'err' : string };
export type Result_7 = { 'ok' : Array<CompletionDashboardRow> } |
  { 'err' : string };
export type Result_8 = { 'ok' : Array<ManagerCheckIn> } |
  { 'err' : string };
export type Result_9 = { 'ok' : Array<AchievementReportRow> } |
  { 'err' : string };
export interface ThrustArea {
  'id' : string,
  'name' : string,
  'description' : string,
}
export type Timestamp = bigint;
export type UoMDirection = { 'Max' : null } |
  { 'Min' : null };
export type UoMType = { 'Percent' : null } |
  { 'Numeric' : null } |
  { 'Timeline' : null } |
  { 'ZeroBased' : null };
export interface User {
  'id' : UserId,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'demoKey' : string,
  'managerId' : [] | [UserId],
  'department' : string,
}
export type UserId = Principal;
export type UserRole = { 'Employee' : null } |
  { 'Admin' : null } |
  { 'Manager' : null };
export interface _SERVICE {
  'addCheckInComment' : ActorMethod<
    [string, Principal, CheckInPeriod, string],
    Result_10
  >,
  'adminUnlockGoals' : ActorMethod<[Principal, string], Result_1>,
  'createGoal' : ActorMethod<
    [string, string, string, UoMType, [] | [UoMDirection], number, number],
    Result
  >,
  'getAchievementReport' : ActorMethod<[CheckInPeriod], Result_9>,
  'getAuditLog' : ActorMethod<[[] | [string]], Array<AuditLog>>,
  'getCheckInComments' : ActorMethod<[Principal, CheckInPeriod], Result_8>,
  'getCompletionDashboard' : ActorMethod<[], Result_7>,
  'getCurrentUser' : ActorMethod<[], Result_2>,
  'getEmployeeAchievements' : ActorMethod<[Principal, CheckInPeriod], Result_6>,
  'getEmployeeGoals' : ActorMethod<[Principal], Result_5>,
  'getMyAchievements' : ActorMethod<[CheckInPeriod], Result_6>,
  'getMyGoals' : ActorMethod<[], Result_5>,
  'getMyTeam' : ActorMethod<[], Result_4>,
  'getThrustAreas' : ActorMethod<[], Array<ThrustArea>>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'logAchievement' : ActorMethod<
    [string, CheckInPeriod, number, [] | [bigint], AchievementStatus],
    Result_3
  >,
  'loginAsDemo' : ActorMethod<[string], Result_2>,
  'managerApproveGoals' : ActorMethod<[Principal], Result_1>,
  'managerEditGoal' : ActorMethod<
    [string, [] | [number], [] | [number]],
    Result
  >,
  'managerReturnGoals' : ActorMethod<[Principal, string], Result_1>,
  'pushSharedGoal' : ActorMethod<[string, Array<Principal>], Result_1>,
  'submitGoalsForApproval' : ActorMethod<[], Result_1>,
  'updateGoal' : ActorMethod<
    [string, string, string, UoMType, [] | [UoMDirection], number, number],
    Result
  >,
  'updateSharedGoalWeightage' : ActorMethod<[string, number], Result>,
  'whoami' : ActorMethod<[], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];