/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ThrustArea {
    id: string;
    name: string;
    description: string;
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
};
export interface AuditLog {
    id: string;
    field: string;
    changedByName: string;
    oldValue: string;
    changedBy: UserId;
    newValue: string;
    goalId: string;
    timestamp: Timestamp;
}
export type Result_6 = {
    __kind__: "ok";
    ok: Array<Achievement>;
} | {
    __kind__: "err";
    err: string;
};
export interface User {
    id: UserId;
    name: string;
    role: UserRole;
    email: string;
    demoKey: string;
    managerId?: UserId;
    department: string;
}
export type Result_5 = {
    __kind__: "ok";
    ok: Array<Goal>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_9 = {
    __kind__: "ok";
    ok: Array<AchievementReportRow>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface Achievement {
    id: string;
    actual: number;
    completionDate?: Timestamp;
    period: CheckInPeriod;
    progressScore: number;
    goalId: string;
    achievementStatus: AchievementStatus;
    updatedAt: Timestamp;
    employeeId: UserId;
}
export type Result_4 = {
    __kind__: "ok";
    ok: Array<User>;
} | {
    __kind__: "err";
    err: string;
};
export type UserId = Principal;
export type Result = {
    __kind__: "ok";
    ok: Goal;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Achievement;
} | {
    __kind__: "err";
    err: string;
};
export type Result_10 = {
    __kind__: "ok";
    ok: ManagerCheckIn;
} | {
    __kind__: "err";
    err: string;
};
export type Result_8 = {
    __kind__: "ok";
    ok: Array<ManagerCheckIn>;
} | {
    __kind__: "err";
    err: string;
};
export interface AchievementReportRow {
    user: User;
    achievements: Array<Achievement>;
    goals: Array<Goal>;
}
export type Result_7 = {
    __kind__: "ok";
    ok: Array<CompletionDashboardRow>;
} | {
    __kind__: "err";
    err: string;
};
export interface ManagerCheckIn {
    id: string;
    period: CheckInPeriod;
    createdAt: Timestamp;
    goalId: string;
    comment: string;
    employeeId: UserId;
    managerId: UserId;
}
export interface CompletionDashboardRow {
    q2Done: boolean;
    submitted: boolean;
    q4Done: boolean;
    user: User;
    q1Done: boolean;
    approved: boolean;
    q3Done: boolean;
}
export interface Goal {
    id: string;
    status: GoalStatus;
    weightage: number;
    title: string;
    createdAt: Timestamp;
    uomType: UoMType;
    description: string;
    sharedFromId?: string;
    isShared: boolean;
    uomDirection?: UoMDirection;
    updatedAt: Timestamp;
    target: number;
    employeeId: UserId;
    thrustAreaId: string;
}
export enum AchievementStatus {
    OnTrack = "OnTrack",
    Completed = "Completed",
    NotStarted = "NotStarted"
}
export enum CheckInPeriod {
    Q1 = "Q1",
    Q2 = "Q2",
    Q3 = "Q3",
    Q4Annual = "Q4Annual"
}
export enum GoalStatus {
    ApprovedLocked = "ApprovedLocked",
    UnderReview = "UnderReview",
    Draft = "Draft",
    ReturnedForRework = "ReturnedForRework",
    Submitted = "Submitted"
}
export enum UoMDirection {
    Max = "Max",
    Min = "Min"
}
export enum UoMType {
    Percent = "Percent",
    Numeric = "Numeric",
    Timeline = "Timeline",
    ZeroBased = "ZeroBased"
}
export enum UserRole {
    Employee = "Employee",
    Admin = "Admin",
    Manager = "Manager"
}
export interface backendInterface {
    addCheckInComment(goalId: string, employeeId: Principal, period: CheckInPeriod, comment: string): Promise<Result_10>;
    adminUnlockGoals(employeeId: Principal, reason: string): Promise<Result_1>;
    createGoal(thrustAreaId: string, title: string, description: string, uomType: UoMType, uomDirection: UoMDirection | null, target: number, weightage: number): Promise<Result>;
    getAchievementReport(period: CheckInPeriod): Promise<Result_9>;
    getAuditLog(goalId: string | null): Promise<Array<AuditLog>>;
    getCheckInComments(employeeId: Principal, period: CheckInPeriod): Promise<Result_8>;
    getCompletionDashboard(): Promise<Result_7>;
    getCurrentUser(): Promise<Result_2>;
    getEmployeeAchievements(employeeId: Principal, period: CheckInPeriod): Promise<Result_6>;
    getEmployeeGoals(employeeId: Principal): Promise<Result_5>;
    getMyAchievements(period: CheckInPeriod): Promise<Result_6>;
    getMyGoals(): Promise<Result_5>;
    getMyTeam(): Promise<Result_4>;
    getThrustAreas(): Promise<Array<ThrustArea>>;
    getUsers(): Promise<Array<User>>;
    logAchievement(goalId: string, period: CheckInPeriod, actual: number, completionDate: bigint | null, achievementStatus: AchievementStatus): Promise<Result_3>;
    loginAsDemo(demoKey: string): Promise<Result_2>;
    managerApproveGoals(employeeId: Principal): Promise<Result_1>;
    managerEditGoal(goalId: string, target: number | null, weightage: number | null): Promise<Result>;
    managerReturnGoals(employeeId: Principal, reason: string): Promise<Result_1>;
    pushSharedGoal(sourceGoalId: string, employeeIds: Array<Principal>): Promise<Result_1>;
    submitGoalsForApproval(): Promise<Result_1>;
    updateGoal(goalId: string, title: string, description: string, uomType: UoMType, uomDirection: UoMDirection | null, target: number, weightage: number): Promise<Result>;
    updateSharedGoalWeightage(goalId: string, weightage: number): Promise<Result>;
    whoami(): Promise<Principal>;
}
import type { Achievement as _Achievement, AchievementReportRow as _AchievementReportRow, AchievementStatus as _AchievementStatus, CheckInPeriod as _CheckInPeriod, CompletionDashboardRow as _CompletionDashboardRow, Goal as _Goal, GoalStatus as _GoalStatus, ManagerCheckIn as _ManagerCheckIn, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, Timestamp as _Timestamp, UoMDirection as _UoMDirection, UoMType as _UoMType, User as _User, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCheckInComment(arg0: string, arg1: Principal, arg2: CheckInPeriod, arg3: string): Promise<Result_10> {
        if (this.processError) {
            try {
                const result = await this.actor.addCheckInComment(arg0, arg1, to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Result_10_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCheckInComment(arg0, arg1, to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Result_10_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUnlockGoals(arg0: Principal, arg1: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnlockGoals(arg0, arg1);
                return from_candid_Result_1_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnlockGoals(arg0, arg1);
            return from_candid_Result_1_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGoal(arg0: string, arg1: string, arg2: string, arg3: UoMType, arg4: UoMDirection | null, arg5: number, arg6: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0, arg1, arg2, to_candid_UoMType_n11(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return from_candid_Result_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0, arg1, arg2, to_candid_UoMType_n11(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return from_candid_Result_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAchievementReport(arg0: CheckInPeriod): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievementReport(to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_9_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievementReport(to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_9_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLog(arg0: string | null): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog(to_candid_opt_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog(to_candid_opt_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCheckInComments(arg0: Principal, arg1: CheckInPeriod): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.getCheckInComments(arg0, to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_8_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCheckInComments(arg0, to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_8_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletionDashboard(): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletionDashboard();
                return from_candid_Result_7_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletionDashboard();
            return from_candid_Result_7_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUser(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return from_candid_Result_2_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return from_candid_Result_2_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeAchievements(arg0: Principal, arg1: CheckInPeriod): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeAchievements(arg0, to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_6_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeAchievements(arg0, to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_6_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeGoals(arg0: Principal): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeGoals(arg0);
                return from_candid_Result_5_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeGoals(arg0);
            return from_candid_Result_5_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAchievements(arg0: CheckInPeriod): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAchievements(to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_6_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAchievements(to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_6_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyGoals(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyGoals();
                return from_candid_Result_5_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyGoals();
            return from_candid_Result_5_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTeam(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTeam();
                return from_candid_Result_4_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTeam();
            return from_candid_Result_4_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getThrustAreas(): Promise<Array<ThrustArea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getThrustAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThrustAreas();
            return result;
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async logAchievement(arg0: string, arg1: CheckInPeriod, arg2: number, arg3: bigint | null, arg4: AchievementStatus): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.logAchievement(arg0, to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n63(this._uploadFile, this._downloadFile, arg3), to_candid_AchievementStatus_n64(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_3_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logAchievement(arg0, to_candid_CheckInPeriod_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n63(this._uploadFile, this._downloadFile, arg3), to_candid_AchievementStatus_n64(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_3_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginAsDemo(arg0: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.loginAsDemo(arg0);
                return from_candid_Result_2_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginAsDemo(arg0);
            return from_candid_Result_2_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async managerApproveGoals(arg0: Principal): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.managerApproveGoals(arg0);
                return from_candid_Result_1_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.managerApproveGoals(arg0);
            return from_candid_Result_1_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async managerEditGoal(arg0: string, arg1: number | null, arg2: number | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.managerEditGoal(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n68(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.managerEditGoal(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n68(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async managerReturnGoals(arg0: Principal, arg1: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.managerReturnGoals(arg0, arg1);
                return from_candid_Result_1_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.managerReturnGoals(arg0, arg1);
            return from_candid_Result_1_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async pushSharedGoal(arg0: string, arg1: Array<Principal>): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.pushSharedGoal(arg0, arg1);
                return from_candid_Result_1_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pushSharedGoal(arg0, arg1);
            return from_candid_Result_1_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitGoalsForApproval(): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.submitGoalsForApproval();
                return from_candid_Result_1_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitGoalsForApproval();
            return from_candid_Result_1_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGoal(arg0: string, arg1: string, arg2: string, arg3: UoMType, arg4: UoMDirection | null, arg5: number, arg6: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoal(arg0, arg1, arg2, to_candid_UoMType_n11(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return from_candid_Result_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoal(arg0, arg1, arg2, to_candid_UoMType_n11(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return from_candid_Result_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSharedGoalWeightage(arg0: string, arg1: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSharedGoalWeightage(arg0, arg1);
                return from_candid_Result_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSharedGoalWeightage(arg0, arg1);
            return from_candid_Result_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async whoami(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.whoami();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoami();
            return result;
        }
    }
}
function from_candid_AchievementReportRow_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AchievementReportRow): AchievementReportRow {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_AchievementStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AchievementStatus): AchievementStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Achievement_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Achievement): Achievement {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_CheckInPeriod_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckInPeriod): CheckInPeriod {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_CompletionDashboardRow_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompletionDashboardRow): CompletionDashboardRow {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_GoalStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalStatus): GoalStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ManagerCheckIn_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ManagerCheckIn): ManagerCheckIn {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_10_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_10): Result_10 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UoMDirection_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UoMDirection): UoMDirection {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UoMType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UoMType): UoMType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_User_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UoMDirection]): UoMDirection | null {
    return value.length === 0 ? null : from_candid_UoMDirection_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _GoalStatus;
    weightage: number;
    title: string;
    createdAt: _Timestamp;
    uomType: _UoMType;
    description: string;
    sharedFromId: [] | [string];
    isShared: boolean;
    uomDirection: [] | [_UoMDirection];
    updatedAt: _Timestamp;
    target: number;
    employeeId: _UserId;
    thrustAreaId: string;
}): {
    id: string;
    status: GoalStatus;
    weightage: number;
    title: string;
    createdAt: Timestamp;
    uomType: UoMType;
    description: string;
    sharedFromId?: string;
    isShared: boolean;
    uomDirection?: UoMDirection;
    updatedAt: Timestamp;
    target: number;
    employeeId: UserId;
    thrustAreaId: string;
} {
    return {
        id: value.id,
        status: from_candid_GoalStatus_n20(_uploadFile, _downloadFile, value.status),
        weightage: value.weightage,
        title: value.title,
        createdAt: value.createdAt,
        uomType: from_candid_UoMType_n22(_uploadFile, _downloadFile, value.uomType),
        description: value.description,
        sharedFromId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.sharedFromId)),
        isShared: value.isShared,
        uomDirection: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.uomDirection)),
        updatedAt: value.updatedAt,
        target: value.target,
        employeeId: value.employeeId,
        thrustAreaId: value.thrustAreaId
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: _User;
    achievements: Array<_Achievement>;
    goals: Array<_Goal>;
}): {
    user: User;
    achievements: Array<Achievement>;
    goals: Array<Goal>;
} {
    return {
        user: from_candid_User_n33(_uploadFile, _downloadFile, value.user),
        achievements: from_candid_vec_n38(_uploadFile, _downloadFile, value.achievements),
        goals: from_candid_vec_n44(_uploadFile, _downloadFile, value.goals)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    role: _UserRole;
    email: string;
    demoKey: string;
    managerId: [] | [_UserId];
    department: string;
}): {
    id: UserId;
    name: string;
    role: UserRole;
    email: string;
    demoKey: string;
    managerId?: UserId;
    department: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_UserRole_n35(_uploadFile, _downloadFile, value.role),
        email: value.email,
        demoKey: value.demoKey,
        managerId: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.managerId)),
        department: value.department
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    actual: number;
    completionDate: [] | [_Timestamp];
    period: _CheckInPeriod;
    progressScore: number;
    goalId: string;
    achievementStatus: _AchievementStatus;
    updatedAt: _Timestamp;
    employeeId: _UserId;
}): {
    id: string;
    actual: number;
    completionDate?: Timestamp;
    period: CheckInPeriod;
    progressScore: number;
    goalId: string;
    achievementStatus: AchievementStatus;
    updatedAt: Timestamp;
    employeeId: UserId;
} {
    return {
        id: value.id,
        actual: value.actual,
        completionDate: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.completionDate)),
        period: from_candid_CheckInPeriod_n7(_uploadFile, _downloadFile, value.period),
        progressScore: value.progressScore,
        goalId: value.goalId,
        achievementStatus: from_candid_AchievementStatus_n42(_uploadFile, _downloadFile, value.achievementStatus),
        updatedAt: value.updatedAt,
        employeeId: value.employeeId
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    q2Done: boolean;
    submitted: boolean;
    q4Done: boolean;
    user: _User;
    q1Done: boolean;
    approved: boolean;
    q3Done: boolean;
}): {
    q2Done: boolean;
    submitted: boolean;
    q4Done: boolean;
    user: User;
    q1Done: boolean;
    approved: boolean;
    q3Done: boolean;
} {
    return {
        q2Done: value.q2Done,
        submitted: value.submitted,
        q4Done: value.q4Done,
        user: from_candid_User_n33(_uploadFile, _downloadFile, value.user),
        q1Done: value.q1Done,
        approved: value.approved,
        q3Done: value.q3Done
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    period: _CheckInPeriod;
    createdAt: _Timestamp;
    goalId: string;
    comment: string;
    employeeId: _UserId;
    managerId: _UserId;
}): {
    id: string;
    period: CheckInPeriod;
    createdAt: Timestamp;
    goalId: string;
    comment: string;
    employeeId: UserId;
    managerId: UserId;
} {
    return {
        id: value.id,
        period: from_candid_CheckInPeriod_n7(_uploadFile, _downloadFile, value.period),
        createdAt: value.createdAt,
        goalId: value.goalId,
        comment: value.comment,
        employeeId: value.employeeId,
        managerId: value.managerId
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Goal;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Goal;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Goal_n18(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ApprovedLocked: null;
} | {
    UnderReview: null;
} | {
    Draft: null;
} | {
    ReturnedForRework: null;
} | {
    Submitted: null;
}): GoalStatus {
    return "ApprovedLocked" in value ? GoalStatus.ApprovedLocked : "UnderReview" in value ? GoalStatus.UnderReview : "Draft" in value ? GoalStatus.Draft : "ReturnedForRework" in value ? GoalStatus.ReturnedForRework : "Submitted" in value ? GoalStatus.Submitted : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Percent: null;
} | {
    Numeric: null;
} | {
    Timeline: null;
} | {
    ZeroBased: null;
}): UoMType {
    return "Percent" in value ? UoMType.Percent : "Numeric" in value ? UoMType.Numeric : "Timeline" in value ? UoMType.Timeline : "ZeroBased" in value ? UoMType.ZeroBased : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Max: null;
} | {
    Min: null;
}): UoMDirection {
    return "Max" in value ? UoMDirection.Max : "Min" in value ? UoMDirection.Min : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_AchievementReportRow>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<AchievementReportRow>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n30(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Employee: null;
} | {
    Admin: null;
} | {
    Manager: null;
}): UserRole {
    return "Employee" in value ? UserRole.Employee : "Admin" in value ? UserRole.Admin : "Manager" in value ? UserRole.Manager : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ManagerCheckIn;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ManagerCheckIn;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ManagerCheckIn_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OnTrack: null;
} | {
    Completed: null;
} | {
    NotStarted: null;
}): AchievementStatus {
    return "OnTrack" in value ? AchievementStatus.OnTrack : "Completed" in value ? AchievementStatus.Completed : "NotStarted" in value ? AchievementStatus.NotStarted : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_ManagerCheckIn>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<ManagerCheckIn>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n48(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_CompletionDashboardRow>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<CompletionDashboardRow>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n51(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n33(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Achievement>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Achievement>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n38(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_Goal>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<Goal>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n44(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_User>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<User>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n62(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Achievement;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Achievement;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Achievement_n39(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Q1: null;
} | {
    Q2: null;
} | {
    Q3: null;
} | {
    Q4Annual: null;
}): CheckInPeriod {
    return "Q1" in value ? CheckInPeriod.Q1 : "Q2" in value ? CheckInPeriod.Q2 : "Q3" in value ? CheckInPeriod.Q3 : "Q4Annual" in value ? CheckInPeriod.Q4Annual : value;
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AchievementReportRow>): Array<AchievementReportRow> {
    return value.map((x)=>from_candid_AchievementReportRow_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Achievement>): Array<Achievement> {
    return value.map((x)=>from_candid_Achievement_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ManagerCheckIn>): Array<ManagerCheckIn> {
    return value.map((x)=>from_candid_ManagerCheckIn_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompletionDashboardRow>): Array<CompletionDashboardRow> {
    return value.map((x)=>from_candid_CompletionDashboardRow_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n33(_uploadFile, _downloadFile, x));
}
function to_candid_AchievementStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AchievementStatus): _AchievementStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_CheckInPeriod_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckInPeriod): _CheckInPeriod {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UoMDirection_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UoMDirection): _UoMDirection {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UoMType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UoMType): _UoMType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UoMDirection | null): [] | [_UoMDirection] {
    return value === null ? candid_none() : candid_some(to_candid_UoMDirection_n14(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UoMType): {
    Percent: null;
} | {
    Numeric: null;
} | {
    Timeline: null;
} | {
    ZeroBased: null;
} {
    return value == UoMType.Percent ? {
        Percent: null
    } : value == UoMType.Numeric ? {
        Numeric: null
    } : value == UoMType.Timeline ? {
        Timeline: null
    } : value == UoMType.ZeroBased ? {
        ZeroBased: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UoMDirection): {
    Max: null;
} | {
    Min: null;
} {
    return value == UoMDirection.Max ? {
        Max: null
    } : value == UoMDirection.Min ? {
        Min: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckInPeriod): {
    Q1: null;
} | {
    Q2: null;
} | {
    Q3: null;
} | {
    Q4Annual: null;
} {
    return value == CheckInPeriod.Q1 ? {
        Q1: null
    } : value == CheckInPeriod.Q2 ? {
        Q2: null
    } : value == CheckInPeriod.Q3 ? {
        Q3: null
    } : value == CheckInPeriod.Q4Annual ? {
        Q4Annual: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AchievementStatus): {
    OnTrack: null;
} | {
    Completed: null;
} | {
    NotStarted: null;
} {
    return value == AchievementStatus.OnTrack ? {
        OnTrack: null
    } : value == AchievementStatus.Completed ? {
        Completed: null
    } : value == AchievementStatus.NotStarted ? {
        NotStarted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
